4679. Use LegacyWithBuckets for histograms.
remerge/go-service pull request #74
Opened 2020-11-18 13:39 UTC by thekondor

## Context

This PR leverages the latest changes of so called "lock free" Sample to collect histogram's values to corresponding buckets (currently they are predefined, see the related PR).

Dependent PR: https://github.com/remerge/go-lock_free_timer/pull/3

2020-11-18 13:40 UTC, thekondor commented on prom_metrics.go
> +	case lft_sample.LegacyWithBuckets:
as discussed with @akaspin, we're ok with casting an extra interface to retrieve the new values for a further processing (serialization)

2020-11-19 11:17 UTC, akaspin commented on prom_metrics.go
> +	default:
We don't need to assert the old one. For now summary should be always exported. In case of `LegacyWithBuckets` histogram buckets should be added after summary.

2020-11-19 11:18 UTC, akaspin requested changes

2020-11-19 11:18 UTC, akaspin commented on prom_metrics.go
> +	default:
We don't need to assert the old one. For now summary should be always exported. In case of LegacyWithBuckets histogram buckets should be added after summary.

2020-11-20 12:05 UTC, thekondor commented on metrics.go
> +		lft.NewLockFreeSampleWithBuckets([]float64{0, 58419, 525771, 4731939, 42587451, 383287059, 3449583531}),
these values are based on current min & max `go_runtime_mem_stat_pause_ns` values from Prometheus with some approximation added.

2020-11-20 12:22 UTC, akaspin approved these changes
👍

2020-11-20 13:34 UTC, merged